### ISSUE TITLE
Add custom recipes for Crayfishs' Furniture Mod

### ISSUE THREAD

**Issue by Pikachu298** [PaintNinja/CraftMine#14]
I noticed that Mr.Crayfishs' Furniture Mod has a new feature where you can change or add recipes for all the machines in the mod. You could change in-/output for the microwave or add Stuff to MineBay.
It even features an ingame Recipe Book which keeps track of all the recipes configured in the config. We should definitely consider adding some recipes and compatibility to installed mods.

**Comment by PaintNinja** [comment]
That sounds like a great idea to help bridge the gaps between mods!

**Comment by PaintNinja** [comment]
Deadline missed, feature won't make it to v4.
