### ISSUE TITLE
Add Malisis Adverts Mod

### ISSUE THREAD

**Issue by Pikachu298** [PaintNinja/CraftMine#15]
This mod lets you add advertisement-boards to the game, which would be used to advertise commands and new updates at the servers' spawn!

http://www.curse.com/mc-mods/minecraft/228722-malisisadvert

**Comment by Pikachu298** [comment]
Works perfectly fine too! Use command /malisisadvert to add advertisements (weblinks linking to images).
https://www.youtube.com/watch?v=yYSugT4iNas&feature=youtu.be

**Comment by PaintNinja** [comment]
Dayum son! That's amazing - much better than I originally expected!

**Comment by PaintNinja** [comment]
Implementing it now, skipping initial tests blah blah blah...

**Comment by PaintNinja** [comment]
It seems like this mod and its dependency is marked as "Beta", but after seeing your tests it's likely to be fine.
