### ISSUE TITLE
Add Wallpaper Mod by pau101

### ISSUE THREAD

**Issue by Pikachu298** [PaintNinja/CraftMine#16]
This mod adds custom wallpapers to the game, which are very astethic and look just great in a way vanilla blocks would do! We still need some investigation on compatibility (i hate that word lol).

**Comment by Pikachu298** [comment]
Going to add the mod to a2b0019 and see what kind of compatibility issues are coming up, or if everything runs just fine. Posting results with screencaps later on. (Wallpaper Mod v0.9 for 1.7.10)

**Comment by Pikachu298** [comment]
Everything works fine! Not a single bug detected while trying to add or remove the wallpapers. If you break a block the wallpapers drop too. And you can even hang up Item frames and such against them!

![2015-09-28_20 14 25](https://cloud.githubusercontent.com/assets/14407620/10144395/ad1f81ce-661d-11e5-9fd1-d0acf0c25324.png)

**Comment by PaintNinja** [comment]
Reopened this issue until implemented

**Comment by PaintNinja** [comment]
Implementing the mod into CMA3b0022 and skipping tests because you've already done 'em...

Mod link: http://minecraft.curseforge.com/projects/wallpaper?gameCategorySlug=mc-mods&projectID=233716
