### ISSUE TITLE
Backport MC 1.8 and 1.9 features to CMv4

### ISSUE THREAD

**Issue by PaintNinja** [PaintNinja/CraftMine#27]
CraftMine is usually a version behind MC due to the amount of mods we depend on, but since v3 I think, we have been implementing features from the newer MC versions to make the differences more blurred.

I think it would be a great idea to implement the Et Futurum mod in CMv4, because it's most of the backports are all wrapped up in one mod!

Link: http://minecraft.curseforge.com/projects/et-futurum

**Comment by Pikachu298** [comment]
Tried to add Et Futurum 1.44 to CMv4 b0031 and looks like everything works fine! We can implement it. Stone generation looks nice, still in need for Textures ( We can grab them from 1.8 Faithful 64) and we have to disable the new 1.9 Mob Collide function. It gets pretty annyoing

**Comment by PaintNinja** [comment]
Done - d2c4eef
