### ISSUE TITLE
Add Highlands

### ISSUE THREAD

**Issue by PaintNinja** [PaintNinja/CraftMine#5]
Highlands is a mod that I've loved in CMv3 and wish that it would come over to v4 too, because at the moment just having EBXL isn't really unique...

Just like the "New Dawn" worldgen engine (#3), we'll need to test Highlands' compatibility and stability with EBXL. Highlands also mustn't be too lag spikey.

Link: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2104582-forge-highlands-2-2-3-updated-february-19

**Comment by PaintNinja** [comment]
Confirmed stable and compatible with EBXL. Some minor lag spikes during initial worldgen just like EBXL but once generated the spikes are completely gone.

Highlands has made the terrain more hilly and mountainous and the oceans more interesting with different kinds of ocean depths and sub-biomes like mini tropical islands.

**Comment by Pikachu298** [comment]
Good to hear! :)

**Comment by PaintNinja** [comment]
Thanks :+1:
